// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tag.proto

package tag

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FindTagsRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindTagsRequest) Reset()         { *m = FindTagsRequest{} }
func (m *FindTagsRequest) String() string { return proto.CompactTextString(m) }
func (*FindTagsRequest) ProtoMessage()    {}
func (*FindTagsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_27f545bcde37ecb5, []int{0}
}

func (m *FindTagsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindTagsRequest.Unmarshal(m, b)
}
func (m *FindTagsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindTagsRequest.Marshal(b, m, deterministic)
}
func (m *FindTagsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindTagsRequest.Merge(m, src)
}
func (m *FindTagsRequest) XXX_Size() int {
	return xxx_messageInfo_FindTagsRequest.Size(m)
}
func (m *FindTagsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindTagsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindTagsRequest proto.InternalMessageInfo

func (m *FindTagsRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type FindTagsResponse struct {
	Name                 []string `protobuf:"bytes,1,rep,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindTagsResponse) Reset()         { *m = FindTagsResponse{} }
func (m *FindTagsResponse) String() string { return proto.CompactTextString(m) }
func (*FindTagsResponse) ProtoMessage()    {}
func (*FindTagsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_27f545bcde37ecb5, []int{1}
}

func (m *FindTagsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindTagsResponse.Unmarshal(m, b)
}
func (m *FindTagsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindTagsResponse.Marshal(b, m, deterministic)
}
func (m *FindTagsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindTagsResponse.Merge(m, src)
}
func (m *FindTagsResponse) XXX_Size() int {
	return xxx_messageInfo_FindTagsResponse.Size(m)
}
func (m *FindTagsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindTagsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindTagsResponse proto.InternalMessageInfo

func (m *FindTagsResponse) GetName() []string {
	if m != nil {
		return m.Name
	}
	return nil
}

func init() {
	proto.RegisterType((*FindTagsRequest)(nil), "tag.FindTagsRequest")
	proto.RegisterType((*FindTagsResponse)(nil), "tag.FindTagsResponse")
}

func init() { proto.RegisterFile("tag.proto", fileDescriptor_27f545bcde37ecb5) }

var fileDescriptor_27f545bcde37ecb5 = []byte{
	// 217 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8f, 0xcf, 0x4b, 0xc3, 0x50,
	0x0c, 0xc7, 0xe9, 0x36, 0xc4, 0xe5, 0xa0, 0xf2, 0x50, 0x18, 0x3b, 0xcd, 0x1d, 0x64, 0x07, 0xdb,
	0x07, 0x0a, 0x7a, 0x17, 0xe6, 0xc5, 0x5b, 0xdd, 0xc9, 0x5b, 0xda, 0x86, 0x2c, 0x68, 0x5f, 0x66,
	0x5f, 0xba, 0xfd, 0xfb, 0xe2, 0x1b, 0xfe, 0xa0, 0xb7, 0x0f, 0xe1, 0xfb, 0x4d, 0x3e, 0x81, 0xa9,
	0x21, 0x17, 0xbb, 0x4e, 0x4d, 0xdd, 0xd8, 0x90, 0xe7, 0x0f, 0x2c, 0xb6, 0xed, 0xab, 0xa2, 0xd6,
	0xd6, 0xb7, 0x07, 0xb1, 0x77, 0x3d, 0x78, 0xd6, 0x3c, 0x25, 0xf2, 0x3d, 0x7e, 0x48, 0x83, 0xa6,
	0x5d, 0xf4, 0xbf, 0x78, 0x2c, 0x2f, 0xaf, 0xe1, 0xfc, 0x59, 0x42, 0xb3, 0x41, 0x8e, 0x25, 0x7d,
	0xf6, 0x14, 0xcd, 0x9d, 0xc1, 0x48, 0x9a, 0x59, 0xb6, 0xc8, 0x56, 0x93, 0x72, 0x24, 0xcd, 0xf2,
	0x06, 0x2e, 0xfe, 0x22, 0x71, 0xa7, 0x21, 0x92, 0x73, 0x30, 0x09, 0xd8, 0xd2, 0x2c, 0x5b, 0x8c,
	0x57, 0xd3, 0x32, 0xf1, 0xdd, 0x1a, 0x60, 0x83, 0xfc, 0x4a, 0xdd, 0x5e, 0x6a, 0x72, 0x8f, 0x70,
	0xfa, 0xd3, 0x72, 0x97, 0xc5, 0xb7, 0xed, 0xe0, 0xce, 0xfc, 0x6a, 0x30, 0x3d, 0xae, 0x7e, 0x2a,
	0xde, 0x6e, 0xff, 0xfd, 0xa2, 0x9d, 0xb0, 0x84, 0x8a, 0x42, 0x30, 0xed, 0xfd, 0x3a, 0x7f, 0x11,
	0xab, 0xb7, 0x14, 0x7c, 0xb2, 0xf7, 0x86, 0x5c, 0x9d, 0x24, 0xbc, 0xff, 0x0a, 0x00, 0x00, 0xff,
	0xff, 0x58, 0xa1, 0x3c, 0xea, 0x12, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TagServiceClient is the client API for TagService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TagServiceClient interface {
	FindTags(ctx context.Context, in *FindTagsRequest, opts ...grpc.CallOption) (*FindTagsResponse, error)
}

type tagServiceClient struct {
	cc *grpc.ClientConn
}

func NewTagServiceClient(cc *grpc.ClientConn) TagServiceClient {
	return &tagServiceClient{cc}
}

func (c *tagServiceClient) FindTags(ctx context.Context, in *FindTagsRequest, opts ...grpc.CallOption) (*FindTagsResponse, error) {
	out := new(FindTagsResponse)
	err := c.cc.Invoke(ctx, "/tag.TagService/FindTags", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TagServiceServer is the server API for TagService service.
type TagServiceServer interface {
	FindTags(context.Context, *FindTagsRequest) (*FindTagsResponse, error)
}

// UnimplementedTagServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTagServiceServer struct {
}

func (*UnimplementedTagServiceServer) FindTags(ctx context.Context, req *FindTagsRequest) (*FindTagsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindTags not implemented")
}

func RegisterTagServiceServer(s *grpc.Server, srv TagServiceServer) {
	s.RegisterService(&_TagService_serviceDesc, srv)
}

func _TagService_FindTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TagServiceServer).FindTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tag.TagService/FindTags",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TagServiceServer).FindTags(ctx, req.(*FindTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TagService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tag.TagService",
	HandlerType: (*TagServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindTags",
			Handler:    _TagService_FindTags_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tag.proto",
}
