// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tag.proto

package tag

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *FindTagsRequest) Validate() error {
	return nil
}
func (this *FindTagsResponse) Validate() error {
	return nil
}
func (this *RegisterTagRequest) Validate() error {
	return nil
}
func (this *RegisterTagResponse) Validate() error {
	return nil
}
