DROP DATABASE IF EXISTS account;
CREATE DATABASE account;

use account

DROP TABLE IF EXISTS user;
CREATE TABLE user (
  id INT unsigned NOT NULL auto_increment,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(1023) NOT NULL,
  created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
