#apiVersion: storage.k8s.io/v1
#kind: StorageClass
#metadata:
#  name: ss-db
#provisioner: kubernetes.io/no-provisioner # Dynamic Provisioningが非サポートとのため、kubernetes.io/no-provisionerを指定
#---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: e-kitchen-pv
  labels:
    type: local
spec:
  storageClassName: ss-db
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/data/e-kitchen-pv"
