apiVersion: v1
kind: Service
metadata:
  name: e-kitchen-user
  labels:
    app: user
spec:
  ports:
    - port: 50051
  selector:
    app: user
    tier: backend
  type: LoadBalancer
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: e-kitchen-user
  labels:
    app: user
spec:
  selector:
    matchLabels:
      app: user
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: user
        tier: backend
    spec:
      containers:
        - image: originbenntou/e-kitchen-user
          name: e-kitchen-user
          ports:
            - containerPort: 50051
          env:
            - name: DB_HOST
              value: e-kitchen-mysql
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
            - name: DB_NAME
              value: e_kitchen
