// Code generated by protoc-gen-go. DO NOT EDIT.
// source: shop.proto

package shop

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/mwitkow/go-proto-validators"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Status int32

const (
	Status_PUBLIC  Status = 0
	Status_PRIVATE Status = 1
	Status_DELETED Status = 2
)

var Status_name = map[int32]string{
	0: "PUBLIC",
	1: "PRIVATE",
	2: "DELETED",
}

var Status_value = map[string]int32{
	"PUBLIC":  0,
	"PRIVATE": 1,
	"DELETED": 2,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0f3030369b20fd61, []int{0}
}

type Shop struct {
	Id                   uint64               `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status               Status               `protobuf:"varint,3,opt,name=status,proto3,enum=shop.Status" json:"status,omitempty"`
	CategoryId           uint64               `protobuf:"varint,4,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	UserId               uint64               `protobuf:"varint,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Shop) Reset()         { *m = Shop{} }
func (m *Shop) String() string { return proto.CompactTextString(m) }
func (*Shop) ProtoMessage()    {}
func (*Shop) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f3030369b20fd61, []int{0}
}

func (m *Shop) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Shop.Unmarshal(m, b)
}
func (m *Shop) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Shop.Marshal(b, m, deterministic)
}
func (m *Shop) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Shop.Merge(m, src)
}
func (m *Shop) XXX_Size() int {
	return xxx_messageInfo_Shop.Size(m)
}
func (m *Shop) XXX_DiscardUnknown() {
	xxx_messageInfo_Shop.DiscardUnknown(m)
}

var xxx_messageInfo_Shop proto.InternalMessageInfo

func (m *Shop) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Shop) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Shop) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_PUBLIC
}

func (m *Shop) GetCategoryId() uint64 {
	if m != nil {
		return m.CategoryId
	}
	return 0
}

func (m *Shop) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Shop) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Shop) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type FindShopsResponse struct {
	Shops                []*Shop  `protobuf:"bytes,1,rep,name=shops,proto3" json:"shops,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindShopsResponse) Reset()         { *m = FindShopsResponse{} }
func (m *FindShopsResponse) String() string { return proto.CompactTextString(m) }
func (*FindShopsResponse) ProtoMessage()    {}
func (*FindShopsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f3030369b20fd61, []int{1}
}

func (m *FindShopsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindShopsResponse.Unmarshal(m, b)
}
func (m *FindShopsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindShopsResponse.Marshal(b, m, deterministic)
}
func (m *FindShopsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindShopsResponse.Merge(m, src)
}
func (m *FindShopsResponse) XXX_Size() int {
	return xxx_messageInfo_FindShopsResponse.Size(m)
}
func (m *FindShopsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindShopsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindShopsResponse proto.InternalMessageInfo

func (m *FindShopsResponse) GetShops() []*Shop {
	if m != nil {
		return m.Shops
	}
	return nil
}

type CreateShopRequest struct {
	Shop                 *Shop    `protobuf:"bytes,1,opt,name=shop,proto3" json:"shop,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateShopRequest) Reset()         { *m = CreateShopRequest{} }
func (m *CreateShopRequest) String() string { return proto.CompactTextString(m) }
func (*CreateShopRequest) ProtoMessage()    {}
func (*CreateShopRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f3030369b20fd61, []int{2}
}

func (m *CreateShopRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateShopRequest.Unmarshal(m, b)
}
func (m *CreateShopRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateShopRequest.Marshal(b, m, deterministic)
}
func (m *CreateShopRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateShopRequest.Merge(m, src)
}
func (m *CreateShopRequest) XXX_Size() int {
	return xxx_messageInfo_CreateShopRequest.Size(m)
}
func (m *CreateShopRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateShopRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateShopRequest proto.InternalMessageInfo

func (m *CreateShopRequest) GetShop() *Shop {
	if m != nil {
		return m.Shop
	}
	return nil
}

type CreateShopResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateShopResponse) Reset()         { *m = CreateShopResponse{} }
func (m *CreateShopResponse) String() string { return proto.CompactTextString(m) }
func (*CreateShopResponse) ProtoMessage()    {}
func (*CreateShopResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f3030369b20fd61, []int{3}
}

func (m *CreateShopResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateShopResponse.Unmarshal(m, b)
}
func (m *CreateShopResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateShopResponse.Marshal(b, m, deterministic)
}
func (m *CreateShopResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateShopResponse.Merge(m, src)
}
func (m *CreateShopResponse) XXX_Size() int {
	return xxx_messageInfo_CreateShopResponse.Size(m)
}
func (m *CreateShopResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateShopResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateShopResponse proto.InternalMessageInfo

func (m *CreateShopResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type UpdateShopRequest struct {
	Shop                 *Shop    `protobuf:"bytes,1,opt,name=shop,proto3" json:"shop,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateShopRequest) Reset()         { *m = UpdateShopRequest{} }
func (m *UpdateShopRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateShopRequest) ProtoMessage()    {}
func (*UpdateShopRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f3030369b20fd61, []int{4}
}

func (m *UpdateShopRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateShopRequest.Unmarshal(m, b)
}
func (m *UpdateShopRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateShopRequest.Marshal(b, m, deterministic)
}
func (m *UpdateShopRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateShopRequest.Merge(m, src)
}
func (m *UpdateShopRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateShopRequest.Size(m)
}
func (m *UpdateShopRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateShopRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateShopRequest proto.InternalMessageInfo

func (m *UpdateShopRequest) GetShop() *Shop {
	if m != nil {
		return m.Shop
	}
	return nil
}

type UpdateShopResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateShopResponse) Reset()         { *m = UpdateShopResponse{} }
func (m *UpdateShopResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateShopResponse) ProtoMessage()    {}
func (*UpdateShopResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f3030369b20fd61, []int{5}
}

func (m *UpdateShopResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateShopResponse.Unmarshal(m, b)
}
func (m *UpdateShopResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateShopResponse.Marshal(b, m, deterministic)
}
func (m *UpdateShopResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateShopResponse.Merge(m, src)
}
func (m *UpdateShopResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateShopResponse.Size(m)
}
func (m *UpdateShopResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateShopResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateShopResponse proto.InternalMessageInfo

func (m *UpdateShopResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type DeleteShopRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteShopRequest) Reset()         { *m = DeleteShopRequest{} }
func (m *DeleteShopRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteShopRequest) ProtoMessage()    {}
func (*DeleteShopRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f3030369b20fd61, []int{6}
}

func (m *DeleteShopRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteShopRequest.Unmarshal(m, b)
}
func (m *DeleteShopRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteShopRequest.Marshal(b, m, deterministic)
}
func (m *DeleteShopRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteShopRequest.Merge(m, src)
}
func (m *DeleteShopRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteShopRequest.Size(m)
}
func (m *DeleteShopRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteShopRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteShopRequest proto.InternalMessageInfo

func (m *DeleteShopRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteShopResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteShopResponse) Reset()         { *m = DeleteShopResponse{} }
func (m *DeleteShopResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteShopResponse) ProtoMessage()    {}
func (*DeleteShopResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f3030369b20fd61, []int{7}
}

func (m *DeleteShopResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteShopResponse.Unmarshal(m, b)
}
func (m *DeleteShopResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteShopResponse.Marshal(b, m, deterministic)
}
func (m *DeleteShopResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteShopResponse.Merge(m, src)
}
func (m *DeleteShopResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteShopResponse.Size(m)
}
func (m *DeleteShopResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteShopResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteShopResponse proto.InternalMessageInfo

func (m *DeleteShopResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterEnum("shop.Status", Status_name, Status_value)
	proto.RegisterType((*Shop)(nil), "shop.Shop")
	proto.RegisterType((*FindShopsResponse)(nil), "shop.FindShopsResponse")
	proto.RegisterType((*CreateShopRequest)(nil), "shop.CreateShopRequest")
	proto.RegisterType((*CreateShopResponse)(nil), "shop.CreateShopResponse")
	proto.RegisterType((*UpdateShopRequest)(nil), "shop.UpdateShopRequest")
	proto.RegisterType((*UpdateShopResponse)(nil), "shop.UpdateShopResponse")
	proto.RegisterType((*DeleteShopRequest)(nil), "shop.DeleteShopRequest")
	proto.RegisterType((*DeleteShopResponse)(nil), "shop.DeleteShopResponse")
}

func init() { proto.RegisterFile("shop.proto", fileDescriptor_0f3030369b20fd61) }

var fileDescriptor_0f3030369b20fd61 = []byte{
	// 521 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xc1, 0x6a, 0xdb, 0x40,
	0x10, 0xad, 0x14, 0x47, 0xae, 0xc7, 0x25, 0xd8, 0x7b, 0x68, 0x84, 0x0b, 0x8d, 0x70, 0x7b, 0x10,
	0x05, 0x4b, 0xe0, 0xd0, 0x42, 0xa1, 0x10, 0x9c, 0x58, 0x05, 0xd3, 0x1c, 0x82, 0xec, 0xf4, 0xd0,
	0x4b, 0x90, 0xa5, 0xa9, 0xb4, 0xd4, 0xd2, 0xaa, 0xda, 0x55, 0x42, 0x6e, 0xfd, 0x82, 0x7e, 0x73,
	0xd9, 0x95, 0x14, 0x3b, 0x51, 0xc1, 0xe4, 0x36, 0x3b, 0x6f, 0xde, 0x1b, 0xcf, 0x9b, 0xb1, 0x00,
	0x78, 0xc2, 0x72, 0x27, 0x2f, 0x98, 0x60, 0xa4, 0x23, 0xe3, 0xd1, 0x49, 0xcc, 0x58, 0xbc, 0x41,
	0x57, 0xe5, 0xd6, 0xe5, 0x4f, 0x57, 0xd0, 0x14, 0xb9, 0x08, 0xd2, 0xba, 0x6c, 0xf4, 0xe6, 0x69,
	0x01, 0xa6, 0xb9, 0xb8, 0xaf, 0xc1, 0x4f, 0x31, 0x15, 0x49, 0xb9, 0x76, 0x42, 0x96, 0xba, 0xe9,
	0x1d, 0x15, 0xbf, 0xd8, 0x9d, 0x1b, 0xb3, 0x89, 0x02, 0x27, 0xb7, 0xc1, 0x86, 0x46, 0x81, 0x60,
	0x05, 0x77, 0x1f, 0xc2, 0x8a, 0x37, 0xfe, 0xa3, 0x43, 0x67, 0x99, 0xb0, 0x9c, 0x1c, 0x81, 0x4e,
	0x23, 0x53, 0xb3, 0x34, 0xbb, 0xe3, 0xeb, 0x34, 0x22, 0x04, 0x3a, 0x59, 0x90, 0xa2, 0xa9, 0x5b,
	0x9a, 0xdd, 0xf3, 0x55, 0x4c, 0xde, 0x83, 0xc1, 0x45, 0x20, 0x4a, 0x6e, 0x1e, 0x58, 0x9a, 0x7d,
	0x34, 0x7d, 0xe5, 0xa8, 0x29, 0x96, 0x2a, 0xe7, 0xd7, 0x18, 0x39, 0x81, 0x7e, 0x18, 0x08, 0x8c,
	0x59, 0x71, 0x7f, 0x43, 0x23, 0xb3, 0xa3, 0x24, 0xa1, 0x49, 0x2d, 0x22, 0x72, 0x0c, 0xdd, 0x92,
	0x63, 0x21, 0xc1, 0x43, 0x05, 0x1a, 0xf2, 0xb9, 0x88, 0xc8, 0x67, 0x80, 0xb0, 0xc0, 0x40, 0x60,
	0x74, 0x13, 0x08, 0xd3, 0xb0, 0x34, 0xbb, 0x3f, 0x1d, 0x39, 0xd5, 0xd8, 0x4e, 0x33, 0xb6, 0xb3,
	0x6a, 0x7c, 0xf1, 0x7b, 0x75, 0xf5, 0x4c, 0x48, 0x6a, 0x99, 0x47, 0x0d, 0xb5, 0xbb, 0x9f, 0x5a,
	0x57, 0xcf, 0xc4, 0xf8, 0x23, 0x0c, 0xbf, 0xd2, 0x2c, 0x92, 0x2e, 0x70, 0x1f, 0x79, 0xce, 0x32,
	0x8e, 0xc4, 0x82, 0x43, 0x39, 0x1b, 0x37, 0x35, 0xeb, 0xc0, 0xee, 0x4f, 0xa1, 0x9e, 0x34, 0x61,
	0xb9, 0x5f, 0x01, 0xe3, 0x53, 0x18, 0x5e, 0xa8, 0xf6, 0x2a, 0x89, 0xbf, 0x4b, 0xe4, 0x82, 0xbc,
	0x05, 0xb5, 0x4c, 0xe5, 0xe3, 0x63, 0x96, 0xca, 0x8f, 0x1d, 0x20, 0xbb, 0xa4, 0xba, 0x99, 0x09,
	0x5d, 0x5e, 0x86, 0x21, 0x72, 0xae, 0x88, 0x2f, 0xfd, 0xe6, 0x29, 0x9b, 0x5c, 0xab, 0x1f, 0xfa,
	0xcc, 0x26, 0xbb, 0xa4, 0xbd, 0x4d, 0xde, 0xc1, 0x70, 0x8e, 0x1b, 0x7c, 0xdc, 0xe4, 0xc9, 0x3d,
	0x48, 0xd1, 0xdd, 0xa2, 0x7d, 0xa2, 0x1f, 0x1c, 0x30, 0xaa, 0xbb, 0x20, 0x00, 0xc6, 0xd5, 0xf5,
	0xf9, 0xe5, 0xe2, 0x62, 0xf0, 0x82, 0xf4, 0xa1, 0x7b, 0xe5, 0x2f, 0xbe, 0xcf, 0x56, 0xde, 0x40,
	0x93, 0x8f, 0xb9, 0x77, 0xe9, 0xad, 0xbc, 0xf9, 0x40, 0x9f, 0xfe, 0xd5, 0xa1, 0x2f, 0xa5, 0x97,
	0x58, 0xdc, 0xd2, 0x10, 0xc9, 0x17, 0xe8, 0x3d, 0x6c, 0x85, 0xbc, 0x6e, 0x6d, 0xd2, 0x93, 0xb7,
	0x3f, 0x3a, 0xae, 0x66, 0x6f, 0xaf, 0xef, 0x0c, 0x60, 0xeb, 0x33, 0xa9, 0xcb, 0x5a, 0xeb, 0x1a,
	0x99, 0x6d, 0x60, 0x2b, 0xb0, 0xf5, 0xb0, 0x11, 0x68, 0xad, 0xa2, 0x11, 0xf8, 0x8f, 0xdd, 0x67,
	0x00, 0x5b, 0xbf, 0x1a, 0x81, 0x96, 0xcd, 0x8d, 0x40, 0xdb, 0xda, 0x73, 0xf7, 0xc7, 0x64, 0xe7,
	0x3f, 0xcd, 0x0a, 0x1a, 0xd3, 0x6c, 0x8d, 0x59, 0x26, 0x58, 0xe9, 0x7a, 0x93, 0x6f, 0x54, 0x84,
	0x09, 0x66, 0xd5, 0xc7, 0xc0, 0x95, 0x1a, 0x6b, 0x43, 0xc5, 0xa7, 0xff, 0x02, 0x00, 0x00, 0xff,
	0xff, 0x1c, 0x60, 0xff, 0xbc, 0x5b, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ShopServiceClient is the client API for ShopService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ShopServiceClient interface {
	FindShops(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*FindShopsResponse, error)
	CreateShop(ctx context.Context, in *CreateShopRequest, opts ...grpc.CallOption) (*CreateShopResponse, error)
	UpdateShop(ctx context.Context, in *UpdateShopRequest, opts ...grpc.CallOption) (*UpdateShopResponse, error)
	DeleteShop(ctx context.Context, in *DeleteShopRequest, opts ...grpc.CallOption) (*DeleteShopResponse, error)
}

type shopServiceClient struct {
	cc *grpc.ClientConn
}

func NewShopServiceClient(cc *grpc.ClientConn) ShopServiceClient {
	return &shopServiceClient{cc}
}

func (c *shopServiceClient) FindShops(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*FindShopsResponse, error) {
	out := new(FindShopsResponse)
	err := c.cc.Invoke(ctx, "/shop.ShopService/FindShops", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) CreateShop(ctx context.Context, in *CreateShopRequest, opts ...grpc.CallOption) (*CreateShopResponse, error) {
	out := new(CreateShopResponse)
	err := c.cc.Invoke(ctx, "/shop.ShopService/CreateShop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) UpdateShop(ctx context.Context, in *UpdateShopRequest, opts ...grpc.CallOption) (*UpdateShopResponse, error) {
	out := new(UpdateShopResponse)
	err := c.cc.Invoke(ctx, "/shop.ShopService/UpdateShop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) DeleteShop(ctx context.Context, in *DeleteShopRequest, opts ...grpc.CallOption) (*DeleteShopResponse, error) {
	out := new(DeleteShopResponse)
	err := c.cc.Invoke(ctx, "/shop.ShopService/DeleteShop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShopServiceServer is the server API for ShopService service.
type ShopServiceServer interface {
	FindShops(context.Context, *empty.Empty) (*FindShopsResponse, error)
	CreateShop(context.Context, *CreateShopRequest) (*CreateShopResponse, error)
	UpdateShop(context.Context, *UpdateShopRequest) (*UpdateShopResponse, error)
	DeleteShop(context.Context, *DeleteShopRequest) (*DeleteShopResponse, error)
}

// UnimplementedShopServiceServer can be embedded to have forward compatible implementations.
type UnimplementedShopServiceServer struct {
}

func (*UnimplementedShopServiceServer) FindShops(ctx context.Context, req *empty.Empty) (*FindShopsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindShops not implemented")
}
func (*UnimplementedShopServiceServer) CreateShop(ctx context.Context, req *CreateShopRequest) (*CreateShopResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateShop not implemented")
}
func (*UnimplementedShopServiceServer) UpdateShop(ctx context.Context, req *UpdateShopRequest) (*UpdateShopResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateShop not implemented")
}
func (*UnimplementedShopServiceServer) DeleteShop(ctx context.Context, req *DeleteShopRequest) (*DeleteShopResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteShop not implemented")
}

func RegisterShopServiceServer(s *grpc.Server, srv ShopServiceServer) {
	s.RegisterService(&_ShopService_serviceDesc, srv)
}

func _ShopService_FindShops_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).FindShops(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shop.ShopService/FindShops",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).FindShops(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_CreateShop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateShopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).CreateShop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shop.ShopService/CreateShop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).CreateShop(ctx, req.(*CreateShopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_UpdateShop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateShopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).UpdateShop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shop.ShopService/UpdateShop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).UpdateShop(ctx, req.(*UpdateShopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_DeleteShop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteShopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).DeleteShop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shop.ShopService/DeleteShop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).DeleteShop(ctx, req.(*DeleteShopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ShopService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "shop.ShopService",
	HandlerType: (*ShopServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindShops",
			Handler:    _ShopService_FindShops_Handler,
		},
		{
			MethodName: "CreateShop",
			Handler:    _ShopService_CreateShop_Handler,
		},
		{
			MethodName: "UpdateShop",
			Handler:    _ShopService_UpdateShop_Handler,
		},
		{
			MethodName: "DeleteShop",
			Handler:    _ShopService_DeleteShop_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shop.proto",
}
