// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: shop.proto

package shop

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/mwitkow/go-proto-validators"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *Shop) Validate() error {
	if this.CreatedAt != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.CreatedAt); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("CreatedAt", err)
		}
	}
	if this.UpdatedAt != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.UpdatedAt); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("UpdatedAt", err)
		}
	}
	return nil
}
func (this *FindShopsResponse) Validate() error {
	for _, item := range this.Shops {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Shops", err)
			}
		}
	}
	return nil
}
func (this *UpdateShopRequest) Validate() error {
	if this.Shop != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Shop); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Shop", err)
		}
	}
	return nil
}
func (this *UpdateShopResponse) Validate() error {
	return nil
}
