// Code generated by protoc-gen-go. DO NOT EDIT.
// source: shop.proto

package shop

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/mwitkow/go-proto-validators"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Status int32

const (
	Status_UNKNOWN   Status = 0
	Status_WAITING   Status = 1
	Status_WORKING   Status = 2
	Status_COMPLETED Status = 3
)

var Status_name = map[int32]string{
	0: "UNKNOWN",
	1: "WAITING",
	2: "WORKING",
	3: "COMPLETED",
}

var Status_value = map[string]int32{
	"UNKNOWN":   0,
	"WAITING":   1,
	"WORKING":   2,
	"COMPLETED": 3,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0f3030369b20fd61, []int{0}
}

type Shop struct {
	Id                   uint64               `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status               Status               `protobuf:"varint,3,opt,name=status,proto3,enum=shop.Status" json:"status,omitempty"`
	CategoryId           uint64               `protobuf:"varint,4,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	UserId               uint64               `protobuf:"varint,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Shop) Reset()         { *m = Shop{} }
func (m *Shop) String() string { return proto.CompactTextString(m) }
func (*Shop) ProtoMessage()    {}
func (*Shop) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f3030369b20fd61, []int{0}
}

func (m *Shop) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Shop.Unmarshal(m, b)
}
func (m *Shop) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Shop.Marshal(b, m, deterministic)
}
func (m *Shop) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Shop.Merge(m, src)
}
func (m *Shop) XXX_Size() int {
	return xxx_messageInfo_Shop.Size(m)
}
func (m *Shop) XXX_DiscardUnknown() {
	xxx_messageInfo_Shop.DiscardUnknown(m)
}

var xxx_messageInfo_Shop proto.InternalMessageInfo

func (m *Shop) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Shop) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Shop) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_UNKNOWN
}

func (m *Shop) GetCategoryId() uint64 {
	if m != nil {
		return m.CategoryId
	}
	return 0
}

func (m *Shop) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Shop) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Shop) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type FindShopsResponse struct {
	Shops                []*Shop  `protobuf:"bytes,1,rep,name=shops,proto3" json:"shops,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindShopsResponse) Reset()         { *m = FindShopsResponse{} }
func (m *FindShopsResponse) String() string { return proto.CompactTextString(m) }
func (*FindShopsResponse) ProtoMessage()    {}
func (*FindShopsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f3030369b20fd61, []int{1}
}

func (m *FindShopsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindShopsResponse.Unmarshal(m, b)
}
func (m *FindShopsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindShopsResponse.Marshal(b, m, deterministic)
}
func (m *FindShopsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindShopsResponse.Merge(m, src)
}
func (m *FindShopsResponse) XXX_Size() int {
	return xxx_messageInfo_FindShopsResponse.Size(m)
}
func (m *FindShopsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindShopsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindShopsResponse proto.InternalMessageInfo

func (m *FindShopsResponse) GetShops() []*Shop {
	if m != nil {
		return m.Shops
	}
	return nil
}

func init() {
	proto.RegisterEnum("shop.Status", Status_name, Status_value)
	proto.RegisterType((*Shop)(nil), "shop.Shop")
	proto.RegisterType((*FindShopsResponse)(nil), "shop.FindShopsResponse")
}

func init() { proto.RegisterFile("shop.proto", fileDescriptor_0f3030369b20fd61) }

var fileDescriptor_0f3030369b20fd61 = []byte{
	// 419 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x41, 0x8b, 0xd3, 0x40,
	0x14, 0x36, 0x69, 0x36, 0xa5, 0x2f, 0xba, 0xd4, 0x39, 0xb8, 0xa1, 0x1e, 0x36, 0x2c, 0x1e, 0x82,
	0xd0, 0x0c, 0x54, 0x14, 0x04, 0x11, 0xaa, 0x56, 0x29, 0xd5, 0x56, 0xd2, 0xca, 0x82, 0x97, 0x65,
	0x9a, 0x19, 0x93, 0xc1, 0x4d, 0x26, 0x64, 0x5e, 0x76, 0xd9, 0x9b, 0x3f, 0x5d, 0x66, 0x92, 0x2e,
	0x62, 0x0f, 0x7b, 0x7b, 0xef, 0x7d, 0xdf, 0xf7, 0xf8, 0xbe, 0x99, 0x07, 0xa0, 0x0b, 0x55, 0x27,
	0x75, 0xa3, 0x50, 0x11, 0xcf, 0xd4, 0x93, 0xf3, 0x5c, 0xa9, 0xfc, 0x5a, 0x50, 0x3b, 0xdb, 0xb7,
	0xbf, 0x28, 0xca, 0x52, 0x68, 0x64, 0x65, 0x4f, 0x9b, 0x3c, 0xff, 0x9f, 0x20, 0xca, 0x1a, 0xef,
	0x7a, 0xf0, 0x4d, 0x2e, 0xb1, 0x68, 0xf7, 0x49, 0xa6, 0x4a, 0x5a, 0xde, 0x4a, 0xfc, 0xad, 0x6e,
	0x69, 0xae, 0xa6, 0x16, 0x9c, 0xde, 0xb0, 0x6b, 0xc9, 0x19, 0xaa, 0x46, 0xd3, 0xfb, 0xb2, 0xd3,
	0x5d, 0xfc, 0x71, 0xc1, 0xdb, 0x16, 0xaa, 0x26, 0xa7, 0xe0, 0x4a, 0x1e, 0x3a, 0x91, 0x13, 0x7b,
	0xa9, 0x2b, 0x39, 0x21, 0xe0, 0x55, 0xac, 0x14, 0xa1, 0x1b, 0x39, 0xf1, 0x28, 0xb5, 0x35, 0x79,
	0x01, 0xbe, 0x46, 0x86, 0xad, 0x0e, 0x07, 0x91, 0x13, 0x9f, 0xce, 0x1e, 0x27, 0x36, 0xc5, 0xd6,
	0xce, 0xd2, 0x1e, 0x23, 0xe7, 0x10, 0x64, 0x0c, 0x45, 0xae, 0x9a, 0xbb, 0x2b, 0xc9, 0x43, 0xcf,
	0xae, 0x84, 0xc3, 0x68, 0xc9, 0xc9, 0x19, 0x0c, 0x5b, 0x2d, 0x1a, 0x03, 0x9e, 0x58, 0xd0, 0x37,
	0xed, 0x92, 0x93, 0xb7, 0x00, 0x59, 0x23, 0x18, 0x0a, 0x7e, 0xc5, 0x30, 0xf4, 0x23, 0x27, 0x0e,
	0x66, 0x93, 0xa4, 0x8b, 0x9d, 0x1c, 0x62, 0x27, 0xbb, 0xc3, 0xbb, 0xa4, 0xa3, 0x9e, 0x3d, 0x47,
	0x23, 0x6d, 0x6b, 0x7e, 0x90, 0x0e, 0x1f, 0x96, 0xf6, 0xec, 0x39, 0x5e, 0xbc, 0x86, 0xa7, 0x9f,
	0x65, 0xc5, 0xcd, 0x2b, 0xe8, 0x54, 0xe8, 0x5a, 0x55, 0x5a, 0x90, 0x08, 0x4e, 0x4c, 0x36, 0x1d,
	0x3a, 0xd1, 0x20, 0x0e, 0x66, 0xd0, 0x27, 0x2d, 0x54, 0x9d, 0x76, 0xc0, 0xcb, 0xf7, 0xe0, 0x77,
	0xc1, 0x49, 0x00, 0xc3, 0x1f, 0xeb, 0xd5, 0x7a, 0x73, 0xb9, 0x1e, 0x3f, 0x32, 0xcd, 0xe5, 0x7c,
	0xb9, 0x5b, 0xae, 0xbf, 0x8c, 0x1d, 0xdb, 0x6c, 0xd2, 0x95, 0x69, 0x5c, 0xf2, 0x04, 0x46, 0x1f,
	0x37, 0xdf, 0xbe, 0x7f, 0x5d, 0xec, 0x16, 0x9f, 0xc6, 0x83, 0xd9, 0x0a, 0x02, 0xb3, 0x6e, 0x2b,
	0x9a, 0x1b, 0x99, 0x09, 0xf2, 0x0e, 0x46, 0xf7, 0x2e, 0xc8, 0xb3, 0x23, 0xe7, 0x0b, 0xf3, 0xd7,
	0x93, 0xb3, 0xce, 0xc6, 0x91, 0xdd, 0x0f, 0xf4, 0xe7, 0xf4, 0x9f, 0x03, 0x50, 0x8d, 0xcc, 0x65,
	0xb5, 0x17, 0x55, 0x85, 0xaa, 0xa5, 0x8b, 0xe9, 0x4a, 0x62, 0x56, 0x88, 0xaa, 0xbb, 0x1c, 0x6a,
	0x56, 0xec, 0x7d, 0x5b, 0xbf, 0xfa, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x4c, 0x06, 0xf5, 0xf2, 0x88,
	0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ShopServiceClient is the client API for ShopService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ShopServiceClient interface {
	FindShops(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*FindShopsResponse, error)
}

type shopServiceClient struct {
	cc *grpc.ClientConn
}

func NewShopServiceClient(cc *grpc.ClientConn) ShopServiceClient {
	return &shopServiceClient{cc}
}

func (c *shopServiceClient) FindShops(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*FindShopsResponse, error) {
	out := new(FindShopsResponse)
	err := c.cc.Invoke(ctx, "/shop.ShopService/FindShops", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShopServiceServer is the server API for ShopService service.
type ShopServiceServer interface {
	FindShops(context.Context, *empty.Empty) (*FindShopsResponse, error)
}

// UnimplementedShopServiceServer can be embedded to have forward compatible implementations.
type UnimplementedShopServiceServer struct {
}

func (*UnimplementedShopServiceServer) FindShops(ctx context.Context, req *empty.Empty) (*FindShopsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindShops not implemented")
}

func RegisterShopServiceServer(s *grpc.Server, srv ShopServiceServer) {
	s.RegisterService(&_ShopService_serviceDesc, srv)
}

func _ShopService_FindShops_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).FindShops(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shop.ShopService/FindShops",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).FindShops(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _ShopService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "shop.ShopService",
	HandlerType: (*ShopServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindShops",
			Handler:    _ShopService_FindShops_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shop.proto",
}
