// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   uint64               `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string               `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	PasswordHash         []byte               `protobuf:"bytes,3,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPasswordHash() []byte {
	if m != nil {
		return m.PasswordHash
	}
	return nil
}

func (m *User) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type CreateUserRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             []byte   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateUserRequest) GetPassword() []byte {
	if m != nil {
		return m.Password
	}
	return nil
}

type CreateUserResponce struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponce) Reset()         { *m = CreateUserResponce{} }
func (m *CreateUserResponce) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponce) ProtoMessage()    {}
func (*CreateUserResponce) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *CreateUserResponce) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponce.Unmarshal(m, b)
}
func (m *CreateUserResponce) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponce.Marshal(b, m, deterministic)
}
func (m *CreateUserResponce) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponce.Merge(m, src)
}
func (m *CreateUserResponce) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponce.Size(m)
}
func (m *CreateUserResponce) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponce.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponce proto.InternalMessageInfo

func (m *CreateUserResponce) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "user.User")
	proto.RegisterType((*CreateUserRequest)(nil), "user.CreateUserRequest")
	proto.RegisterType((*CreateUserResponce)(nil), "user.CreateUserResponce")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 302 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0xc9, 0xac, 0xe2, 0xde, 0xa6, 0x60, 0x10, 0x2c, 0x3d, 0x68, 0x99, 0x97, 0x5e, 0xd6,
	0xc0, 0xf4, 0xe2, 0x49, 0x54, 0x06, 0x82, 0xe0, 0x21, 0xea, 0xc5, 0xcb, 0x48, 0xdb, 0x67, 0x1b,
	0x58, 0x9b, 0x9a, 0xa4, 0xfa, 0x4f, 0xf8, 0x47, 0x4b, 0x13, 0xeb, 0x06, 0xbb, 0xbd, 0xef, 0xcb,
	0xc7, 0xf7, 0x7e, 0xbc, 0x00, 0x74, 0x06, 0x75, 0xda, 0x6a, 0x65, 0x15, 0x0d, 0xfa, 0x39, 0xba,
	0x28, 0x95, 0x2a, 0xd7, 0xc8, 0x9c, 0x97, 0x75, 0x1f, 0xcc, 0xca, 0x1a, 0x8d, 0x15, 0x75, 0xeb,
	0x63, 0xb3, 0x1f, 0x02, 0xc1, 0x9b, 0x41, 0x4d, 0x8f, 0x61, 0x24, 0x8b, 0x90, 0xc4, 0x24, 0x09,
	0xf8, 0x48, 0x16, 0xf4, 0x14, 0xf6, 0xb1, 0x16, 0x72, 0x1d, 0x8e, 0x62, 0x92, 0x8c, 0xb9, 0x17,
	0xf4, 0x12, 0x8e, 0x5a, 0x61, 0xcc, 0xb7, 0xd2, 0xc5, 0xaa, 0x12, 0xa6, 0x0a, 0xf7, 0x62, 0x92,
	0x4c, 0xf9, 0x74, 0x30, 0x1f, 0x85, 0xa9, 0xe8, 0x0d, 0x40, 0xae, 0x51, 0x58, 0x2c, 0x56, 0xc2,
	0x86, 0x41, 0x4c, 0x92, 0xc9, 0x22, 0x4a, 0x3d, 0x49, 0x3a, 0x90, 0xa4, 0xaf, 0x03, 0x09, 0x1f,
	0xff, 0xa5, 0xef, 0xec, 0x6c, 0x09, 0x27, 0x0f, 0x4e, 0xf4, 0x4c, 0x1c, 0x3f, 0x3b, 0x34, 0x76,
	0x83, 0x42, 0xb6, 0x51, 0x22, 0x38, 0x1c, 0xb6, 0x3a, 0xc6, 0x29, 0xff, 0xd7, 0xb3, 0x6b, 0xa0,
	0xdb, 0x35, 0xa6, 0x55, 0x4d, 0x8e, 0xf4, 0x1c, 0xdc, 0x51, 0x5c, 0xcd, 0x64, 0x01, 0xa9, 0xbb,
	0x96, 0x4b, 0x38, 0x7f, 0xf1, 0x0c, 0x93, 0x5e, 0xbd, 0xa0, 0xfe, 0x92, 0x39, 0xd2, 0x5b, 0x80,
	0x4d, 0x09, 0x3d, 0xf3, 0xf1, 0x1d, 0xba, 0x28, 0xdc, 0x7d, 0xf0, 0xfb, 0xee, 0xd9, 0xfb, 0xbc,
	0x94, 0xb6, 0xea, 0xb2, 0x34, 0x57, 0x35, 0x53, 0x5a, 0x96, 0xb2, 0xc9, 0xb0, 0x69, 0xac, 0xea,
	0xd8, 0x72, 0xfe, 0x24, 0x6d, 0x5e, 0x61, 0xe3, 0xbf, 0x86, 0xf5, 0x1d, 0xd9, 0x81, 0x9b, 0xaf,
	0x7e, 0x03, 0x00, 0x00, 0xff, 0xff, 0x89, 0x83, 0xde, 0xab, 0xc8, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponce, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponce, error) {
	out := new(CreateUserResponce)
	err := c.cc.Invoke(ctx, "/user.UserService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponce, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) CreateUser(ctx context.Context, req *CreateUserRequest) (*CreateUserResponce, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _UserService_CreateUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
